-- The Marketing Haven: database, access rules, storage, and booking views.
-- Paste this whole file into the Supabase SQL Editor as one migration.

create table if not exists public.brand_reviews (
  id text primary key,
  full_name text not null,
  brand_name text not null,
  email text not null,
  whatsapp text not null,
  main_goal text,
  platform_type text not null check (platform_type in ('website', 'social', 'none')),
  social_platform text,
  social_link text,
  website_url text,
  screenshot_url text,
  haven_score integer check (haven_score between 0 and 100),
  assessment_summary text,
  biggest_leak text,
  biggest_problems text[] default '{}',
  pre_call_briefing text,
  lead_temperature text default 'Cold' check (lead_temperature in ('Hot', 'Warm', 'Cold')),
  is_returning_user boolean default false,
  clicked_booking_link boolean default false,
  clicked_booking_at timestamptz,
  clicked_playbook_link boolean default false,
  clicked_playbook_at timestamptz,
  converted_to_call boolean default false,
  converted_to_purchase boolean default false,
  deal_value numeric,
  utm_source text,
  utm_campaign text,
  referrer_url text,
  device_type text,
  country text,
  city text,
  visit_count integer default 1 check (visit_count > 0),
  first_visit_at timestamptz default now(),
  submitted_at timestamptz default now(),
  days_to_convert integer default 0,
  followup_status text default 'pending' check (followup_status in ('pending', 'contacted', 'booked', 'closed', 'lost')),
  followup_notes text,
  call_booked_at timestamptz,
  welcome_email_sent boolean default false,
  booking_whatsapp_sent boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.haven_sessions (
  id text primary key,
  review_id text references public.brand_reviews(id) on delete set null,
  scope text not null,
  service_id text,
  messages jsonb default '[]'::jsonb,
  current_step text default 'GREETING',
  last_step_reached text,
  total_exchanges integer default 0,
  drop_off_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.link_click_events (
  id bigint generated by default as identity primary key,
  review_id text references public.brand_reviews(id) on delete set null,
  session_id text references public.haven_sessions(id) on delete set null,
  link_type text not null check (link_type in ('booking', 'playbook', 'whatsapp', 'tiktok', 'instagram')),
  clicked_at timestamptz default now()
);

create table if not exists public.strategy_call_bookings (
  id bigint generated by default as identity primary key,
  review_id text references public.brand_reviews(id) on delete set null,
  full_name text not null,
  email text not null,
  whatsapp text not null,
  brand_name text,
  booked_date date not null,
  booked_time text not null check (booked_time in ('5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM')),
  status text default 'confirmed' check (status in ('confirmed', 'cancelled', 'completed', 'no_show')),
  confirmation_email_sent boolean default false,
  confirmation_whatsapp_sent boolean default false,
  whatsapp_message_template text,
  created_at timestamptz default now()
);

-- Prevent two confirmed appointments being made for the same published slot.
create unique index if not exists one_active_booking_per_slot
  on public.strategy_call_bookings (booked_date, booked_time)
  where status <> 'cancelled';

create table if not exists public.cookie_consents (
  id bigint generated by default as identity primary key,
  visitor_id text,
  consented boolean not null,
  created_at timestamptz default now()
);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_brand_reviews_updated_at on public.brand_reviews;
create trigger update_brand_reviews_updated_at
before update on public.brand_reviews
for each row execute procedure public.update_updated_at_column();

drop trigger if exists update_haven_sessions_updated_at on public.haven_sessions;
create trigger update_haven_sessions_updated_at
before update on public.haven_sessions
for each row execute procedure public.update_updated_at_column();

alter table public.brand_reviews enable row level security;
alter table public.haven_sessions enable row level security;
alter table public.link_click_events enable row level security;
alter table public.strategy_call_bookings enable row level security;
alter table public.cookie_consents enable row level security;

drop policy if exists anon_insert_reviews on public.brand_reviews;
create policy anon_insert_reviews on public.brand_reviews for insert to anon with check (true);
drop policy if exists anon_update_reviews on public.brand_reviews;
create policy anon_update_reviews on public.brand_reviews for update to anon using (true) with check (true);
drop policy if exists anon_insert_sessions on public.haven_sessions;
create policy anon_insert_sessions on public.haven_sessions for insert to anon with check (true);
drop policy if exists anon_update_sessions on public.haven_sessions;
create policy anon_update_sessions on public.haven_sessions for update to anon using (true) with check (true);
drop policy if exists anon_insert_clicks on public.link_click_events;
create policy anon_insert_clicks on public.link_click_events for insert to anon with check (true);
drop policy if exists anon_insert_bookings on public.strategy_call_bookings;
create policy anon_insert_bookings on public.strategy_call_bookings for insert to anon with check (true);
drop policy if exists anon_insert_cookies on public.cookie_consents;
create policy anon_insert_cookies on public.cookie_consents for insert to anon with check (true);

drop policy if exists service_all_reviews on public.brand_reviews;
create policy service_all_reviews on public.brand_reviews for all to service_role using (true) with check (true);
drop policy if exists service_all_sessions on public.haven_sessions;
create policy service_all_sessions on public.haven_sessions for all to service_role using (true) with check (true);
drop policy if exists service_all_clicks on public.link_click_events;
create policy service_all_clicks on public.link_click_events for all to service_role using (true) with check (true);
drop policy if exists service_all_bookings on public.strategy_call_bookings;
create policy service_all_bookings on public.strategy_call_bookings for all to service_role using (true) with check (true);
drop policy if exists service_all_cookies on public.cookie_consents;
create policy service_all_cookies on public.cookie_consents for all to service_role using (true) with check (true);

-- This SQL also creates the private Storage bucket requested in the brief.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('tmh-screenshots', 'tmh-screenshots', false, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists anon_upload_screenshots on storage.objects;
create policy anon_upload_screenshots on storage.objects for insert to anon
with check (bucket_id = 'tmh-screenshots');
drop policy if exists service_read_screenshots on storage.objects;
create policy service_read_screenshots on storage.objects for select to service_role
using (bucket_id = 'tmh-screenshots');

create or replace view public.available_booking_slots as
with dates as (
  select generate_series(current_date, current_date + interval '30 days', interval '1 day')::date as slot_date
), slots as (
  select slot_date, unnest(array['5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM']) as slot_time
  from dates where extract(dow from slot_date) between 1 and 5
), booked as (
  select booked_date, booked_time from public.strategy_call_bookings where status <> 'cancelled'
)
select slots.slot_date, slots.slot_time, (booked.booked_date is null) as is_available
from slots left join booked on booked.booked_date = slots.slot_date and booked.booked_time = slots.slot_time
order by slots.slot_date, slots.slot_time;

create or replace view public.admin_lead_overview as
select br.*, hs.total_exchanges, hs.last_step_reached, hs.drop_off_at
from public.brand_reviews br
left join public.haven_sessions hs on hs.review_id = br.id and hs.scope = 'audit'
order by br.created_at desc;

grant select on public.available_booking_slots to anon, authenticated, service_role;
grant select on public.admin_lead_overview to service_role;
