import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText } from 'lucide-react';

export default function TermsOfServiceModal({ isOpen, onClose }) {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 sm:p-6">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />

          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 15 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 15 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="relative w-full max-w-2xl max-h-[85vh] flex flex-col bg-zinc-900 border border-zinc-800 rounded-2xl shadow-2xl z-10 text-zinc-200 overflow-hidden"
          >
            <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-800 bg-zinc-900/50 shrink-0">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-blue-400" />
                <h3 className="text-lg font-bold text-white">Terms of Service</h3>
              </div>
              <button
                onClick={onClose}
                className="p-1 rounded-lg hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="p-6 overflow-y-auto space-y-4 text-sm leading-relaxed text-zinc-300 custom-scrollbar">
              <p className="text-xs text-zinc-500 uppercase font-semibold">Effective Date: August 2026</p>
              
              <h4 className="text-white font-semibold pt-2">1. Operating Scope</h4>
              <p>The Marketing Haven provides strategic marketing education, digital architecture solutions, brand reviews, and product execution blueprints for business owners and emerging creators.</p>

              <h4 className="text-white font-semibold pt-2">2. Intellectual Property</h4>
              <p>All framework content, digital playbooks, branding resources, and custom application code generated by The Marketing Haven remain proprietary intellectual property.</p>

              <h4 className="text-white font-semibold pt-2">3. Service Execution & Consultation</h4>
              <p>Brand evaluations provided by Haven AI and strategy teams offer positioning recommendations based on benchmark analysis. Results depend on execution accuracy by brand owners.</p>

              <h4 className="text-white font-semibold pt-2">4. Digital Product Delivery</h4>
              <p>Purchases made through our digital store or masterclass portals grant access rights directly to the designated client. Digital product sharing without explicit authorization is prohibited.</p>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}